@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic UI_COLOR_T2
participant ":LogicManager" as LogicManager MODEL_COLOR
participant ":AddressBookParser" as AddressBookParser MODEL_COLOR
participant ":CreateCommandParser" as CreateCommandParser MODEL_COLOR
participant "d:CreateCommand" as CreateCommand MODEL_COLOR
participant ":CommandResult" as CommandResult MODEL_COLOR
end box

box Model LOGIC_COLOR_T2
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("create t/01")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("create t/01")
activate AddressBookParser

create CreateCommandParser
AddressBookParser -> CreateCommandParser
activate CreateCommandParser

CreateCommandParser --> AddressBookParser
deactivate CreateCommandParser

AddressBookParser -> CreateCommandParser : parse("t/01")
activate CreateCommandParser

create CreateCommand
CreateCommandParser -> CreateCommand
activate CreateCommand

CreateCommand --> CreateCommandParser : c
deactivate CreateCommand

CreateCommandParser --> AddressBookParser : c
deactivate CreateCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
CreateCommandParser -[hidden]-> AddressBookParser
destroy CreateCommandParser

AddressBookParser --> LogicManager : c
deactivate AddressBookParser

LogicManager -> CreateCommand : execute()
activate CreateCommand

CreateCommand -> CreateCommand : generateGroupNumber()

CreateCommand -> Model : addGroup(newGroup)
activate Model

Model --> CreateCommand
deactivate Model

create CommandResult
CreateCommand -> CommandResult
activate CommandResult

CommandResult --> CreateCommand
deactivate CommandResult

CreateCommand --> LogicManager : result
deactivate CreateCommand

[<--LogicManager
deactivate LogicManager
@enduml
